# Generated by Django 2.2.1 on 2019-05-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=32)),
                ('avatar', models.FileField(blank=True, default='default.jpg', null=True, upload_to='./avatar')),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
