# Generated by Django 2.2.1 on 2019-06-26 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190530_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('age', models.IntegerField(max_length=32)),
                ('email', models.EmailField(max_length=64)),
                ('address', models.CharField(max_length=128)),
                ('c2t', models.ManyToManyField(to='blog.Classes')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('age', models.IntegerField(max_length=32)),
                ('email', models.EmailField(max_length=64)),
                ('address', models.CharField(max_length=128)),
                ('cls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Classes')),
            ],
        ),
    ]
